### ISSUE TITLE
Rewrite Entity API

### ISSUE THREAD

**Issue by WeeSkilz** [PocketServerMP/PocketServer#43]
hi, I'm a message

**Comment by Fireflies** [comment]
:+1:

**Comment by nickrobson** [comment]
No description is a good description. :+1:

**Comment by Serializator** [comment]
:+1:

**Comment by nickrobson** [comment]
I believe this was fixed by #46

**Comment by WeeSkilz** [comment]
@nickrobson the issue runs deeper than that.

**Comment by nickrobson** [comment]
@WeeSkilz would you mind telling me what the issue is then? the lack of a message in the issue report doesn't really help :|

**Comment by Serializator** [comment]
@nickrobson We're already working on it, so the message isn't a problem.
