### ISSUE TITLE
Indentation is 2 spaces, when it (probably?) should be 4.

### ISSUE THREAD

**Issue by nickrobson** [PocketServerMP/PocketServer#54]
Is this intentional?

**Comment by Serializator** [comment]
It's intentional.

**Comment by Fireflies** [comment]
It is indeed intentional. Google style thing.

**Comment by nickrobson** [comment]
Okey dokey. Looks funky.

**Comment by Fireflies** [comment]
Code style is still being worked on, the official profile is severely outdated unfortunately and forks seem to be all over the place. :(

For anyone looking to use the provided style: simply drop it into `~/.IntelliJIdea15/config/codestyles`, creating directories as needed (`codestyles` won't exist by default if memory serves) and replacing 15 with the appropriate version.
